### ISSUE TITLE
(SOLVED) Karbowanec is on the Winning Pathway

### ISSUE THREAD

**Issue by NamecoinGithub** [seredat/karbowanec#216]
Here is my Proof that Karbowanec has chosen the correct Path

https://github.com/litecoin-project/litecoin/issues/893

https://chainz.cryptoid.info/ltc/#!network

Litecoin is not just dominated by ASIC miners and ASIC Pools who probably don't ever care to upgrade to newer Wallets..........so Litecoin Pools are running a Wallet more than 2 years old 18.1 being the last release before MWEB so why would Pools refuse to upgrade?  And does that mean MWEB aren't even being processed without Pool Support IDK it's confusing

![LitecoinLacksUpgrades](https://user-images.githubusercontent.com/130555019/234139905-49143307-7feb-4408-84cd-4209ebabfde5.png)

**Comment by losh11** [comment]
This is not true. Since the activation of MWEB, all pools **must** support MWEB.
This means they **must** run Litecoin Core 0.21.2 or newer. 
Pools whose blocks don't include the relevant MWEB data will be rejected by the network.

**Comment by NamecoinGithub** [comment]
Thanks, so it is a Hard-Fork

Thanks for Reply though and adding to the discussion!


> This is not true. Since the activation of MWEB, all pools **must** support MWEB. This means they **must** run Litecoin Core 0.21.2 or newer. Pools whose blocks don't include the relevant MWEB data will be rejected by the network.

**Comment by losh11** [comment]
lol I just saw your reply cause you closed this issue. Honestly people who don’t know what a hard fork is, shouldn’t be building crypto software. Since you don’t know what a hard fork actually means, here’s a quick definition: 

A hard fork is a chain split, where new and old versions of the network have different consensus rules, so older clients would see a different latest block compared to a new release.

FYI if you didn’t already know, a ‘forced’ upgrade to create/broadcast/validate txs has happened many times with Bitcoin and its fork. For example old versions of Bitcoin Core will not be able to create a valid tx, as newer nodes enforce that you are using low s signatures.

**Comment by NamecoinGithub** [comment]
Well,

I have nothing to do with Crypto Software Development, I am just a Common Miner, who tries to point things out!

And I can guarantee you I know what a Hard-Fork is!

Thanks!

Sent with [Proton Mail](https://proton.me/) secure email.
